### ISSUE TITLE
How to validation and register device

### ISSUE THREAD

**Issue by arno608rw** [BUILT-CoLAB/license-key-manager#28]
In https://github.com/BUILT-CoLAB/license-key-manager#validation Parameters 'payload' how to PublicKey-encrypted message that containts the HardwareID and the Serial Key of the License?

**Comment by jpdias** [comment]
Hello. You have examples on how to do such operations in the folder https://github.com/BUILT-CoLAB/license-key-manager/tree/main/client , with sample code in both c# and python. The public key should be generated in the moment of associating a new device to a product in the UI.

**Comment by arno608rw** [comment]
Thank you.
